### ISSUE TITLE
Item list in Openhab2-out node overlapping other form fields

### ISSUE THREAD

**Issue by benderl** [pdmangel/node-red-contrib-openhab2#39]
Please see attached screenshot. The item searchbox and list are blocking access to the topic and payload fields. I am using node-red v1.0.0.

![Screenshot_20191002_074725](https://user-images.githubusercontent.com/7837691/66020880-f1b18780-e4e8-11e9-804c-676a0b0c67b9.jpg)

**Comment by LordPacDemon** [comment]
Have got the same issue (node-red 1.0.1).
Looks like a problem with the the class "btn-group"

![image](https://user-images.githubusercontent.com/30553921/66253523-ea4ce100-e769-11e9-997e-9248f6c27d61.png)

After I remove the Div class="btn-group"  it looks fine again.
![image](https://user-images.githubusercontent.com/30553921/66253545-8840ab80-e76a-11e9-97e4-56ef4d5a3f34.png)

**Comment by BeNeDeLuX** [comment]
I can confirm this problem. Node-Red 1.0.1

**Comment by Christian-Me** [comment]
Same here. Think it is caused by the multiselect ccs not working inside Node-Red any more.

**Comment by TiggsPanther** [comment]
Also having the same issue.
Also on node-red 1.0.1

**Comment by LordPacDemon** [comment]
A Quickfix for the problem:
https://github.com/QNimbus/node-red-contrib-openhab-v2/issues/14#issuecomment-543554615

**Comment by pdmangel** [comment]
Fixed in v1.1.6 (thx to LordPacDemon's quick fix!)

**Comment by Christian-Me** [comment]
Still not working as before. Much Better now and usable but the nice multiselect ui-element lost it`s dropdown capabilities.
![image](https://user-images.githubusercontent.com/15779507/68712736-a20cb400-059c-11ea-9c2a-156e3082c4b2.png)
